---
title: "merge"
author: "Hyeonho Lee"
date: "2018년 8월 31일"
output: 
  pdf_document: 
  latex_engine: xelatex
html_document: default
word_document:
  highlight: tango
mainfont: NanumGothic
header-includes :
  - \usepackage{kotex}
---


```{r}
setwd('C:/workspace/Github/big_contest/data')
dat1 = read.csv('dat3.csv', stringsAsFactors = F)
dat2 = read.csv('형이평점데이터수정.csv', stringsAsFactors = F)
dat1 = dat1[,-c(1:2, 15, 16)]
dat2 = dat2[,-c(1,4:13,15)]
```



```{r}
library(dplyr)

dat3 = left_join(dat1, dat2, by = c('영화명', '감독'))

write.csv(dat3, 'final_data.csv', row.names = F)

```

```{r}
library(dplyr)
dat = read.csv('C:/workspace/Github/big_contest/data/final_data.csv', stringsAsFactors = F)

dat_score = dat %>% group_by(감독) %>% mutate(감독점수 = mean(전국관객수))
dat_score = dat_score %>% group_by(제작사) %>% mutate(제작사점수 = mean(전국관객수))
dat_score = dat_score %>% group_by(수입사) %>% mutate(수입사점수 = mean(전국관객수))
dat_score = dat_score %>% group_by(배우1) %>% mutate(배우1점수 = mean(전국관객수))
dat_score = dat_score %>% group_by(배우2) %>% mutate(배우2점수 = mean(전국관객수))
dat_score = dat_score %>% group_by(배우3) %>% mutate(배우3점수 = mean(전국관객수))

#dat_score %>% group_by(장르) %>% summarise(mean = mean(전국관객수), n = n()) %>% arrange(desc(mean))

dat_score$국적[dat_score$국적 != '한국' & dat_score$국적 != '미국'] = '3국'
```

```{r}
write.csv(dat_score, 'C:/workspace/Github/big_contest/data/movie_data.csv', row.names = F)
```



```{r}
dat_score_sel = dat_score %>% group_by() %>% select(개봉월, 국적, 전국스크린수, 전국관객수, 별점, 
                                        감독점수, 제작사점수, 수입사점수, 배우1점수, 배우2점수, 배우3점수)

dat_score_sel$개봉월 = as.factor(dat_score_sel$개봉월)
dat_score_sel$국적 = as.factor(dat_score_sel$국적)

ind = sample(1:nrow(dat_score_sel), floor(.75*nrow(dat_score_sel)), replace = F)


train = dat_score_sel[ind,]
test = dat_score_sel[-ind,]


model = lm(전국관객수~., train)
pred = predict(model, test)
sqrt(mean((test$전국관객수-pred)**2))

summary(model)
cor(dat_score_sel[,-(1:2)])



model = glm(전국관객수~., train, family = 'gaussian')
pred = predict(model, test)
sqrt(mean((test$전국관객수-pred)**2))
```

```{r}
# randomForest
dat_score_sel = dat_score %>% group_by() %>% select(개봉월, 국적, 전국스크린수, 전국관객수, 별점, 
                                        감독점수, 제작사점수, 수입사점수, 배우1점수, 배우2점수, 배우3점수)

dat_score_sel$개봉월 = as.factor(dat_score_sel$개봉월)
dat_score_sel$국적 = as.factor(dat_score_sel$국적)


ind = sample(1:nrow(dat_score_sel), floor(.75*nrow(dat_score_sel)), replace = F)


train = dat_score_sel[ind,]
test = dat_score_sel[-ind,]

model = randomForest::randomForest(전국관객수~., train, ntree = 100)
pred = predict(model, test)
sqrt(mean((test$전국관객수-pred)**2))
```

```{r}
# ridge regression
library(glmnet)

dat_score_sel = dat_score %>% group_by() %>% select(개봉월, 국적, 전국스크린수, 전국관객수, 별점, 
                                        감독점수, 제작사점수, 수입사점수, 배우1점수, 배우2점수, 배우3점수)

dat_score_sel$개봉월 = as.factor(dat_score_sel$개봉월)
dat_score_sel$국적 = as.factor(dat_score_sel$국적)

cv.out = cv.glmnet(model.matrix(전국관객수~., train)[,-1], train$전국관객수, alpha=0)
# plot(cv.out)
# cv.out$lambda.min


grid = 10^seq(10,-2,length=100)
model = glmnet(model.matrix(전국관객수~., train)[,-1], train$전국관객수, alpha = 0, lambda = grid)

pred = predict(model, newx = model.matrix(전국관객수~., test)[,-1], s = cv.out$lambda.min)
sqrt(mean((test$전국관객수-pred)**2))


```

```{r}
# lasso regression
library(glmnet)

dat_score_sel = dat_score %>% group_by() %>% select(개봉월, 국적, 전국스크린수, 전국관객수, 별점, 
                                        감독점수, 제작사점수, 수입사점수, 배우1점수, 배우2점수, 배우3점수)

dat_score_sel$개봉월 = as.factor(dat_score_sel$개봉월)
dat_score_sel$국적 = as.factor(dat_score_sel$국적)

cv.out = cv.glmnet(model.matrix(전국관객수~., train)[,-1], train$전국관객수, alpha=1)
# plot(cv.out)
# cv.out$lambda.min

# plot(lasso.mod)
# plot(lasso.mod, xvar = 'lambda', label = TRUE)
grid = 10^seq(10,-2,length=100)
model = glmnet(model.matrix(전국관객수~., train)[,-1], train$전국관객수, alpha = 1, lambda = grid)

pred = predict(model, newx = model.matrix(전국관객수~., test)[,-1], s = cv.out$lambda.min)
sqrt(mean((test$전국관객수-pred)**2))
```

```{r}
# elastic net
library(glmnet)

dat_score_sel = dat_score %>% group_by() %>% select(개봉월, 국적, 전국스크린수, 전국관객수, 별점, 
                                        감독점수, 제작사점수, 수입사점수, 배우1점수, 배우2점수, 배우3점수)

dat_score_sel$개봉월 = as.factor(dat_score_sel$개봉월)
dat_score_sel$국적 = as.factor(dat_score_sel$국적)

cv.out = cv.glmnet(model.matrix(전국관객수~., train)[,-1], train$전국관객수, alpha=0.5)
# plot(cv.out)
# cv.out$lambda.min
grid = 10^seq(10,-2,length=100)
model = glmnet(model.matrix(전국관객수~., train)[,-1], train$전국관객수, alpha = 0.5, lambda = grid)

pred = predict(model, newx = model.matrix(전국관객수~., test)[,-1], s = cv.out$lambda.min)
sqrt(mean((test$전국관객수-pred)**2))
```
















