---
title: "big contest"
author: "Hyeonho Lee"
date: "2018년 8월 29일"
output: 
  pdf_document: 
  latex_engine: xelatex
html_document: default
word_document:
  highlight: tango
mainfont: NanumGothic
header-includes :
  - \usepackage{kotex}
---



```{r warning=FALSE}
library(dplyr)

dat = read.csv('C:/workspace/Github/big_contest/data/dat.csv', stringsAsFactors = FALSE)


# head(dat)
# names(dat)
# str(dat)

dat$전국스크린수 = gsub(',', '', dat$전국스크린수)
dat$전국스크린수 = as.integer(dat$전국스크린수)
dat$전국관객수 = gsub(',', '', dat$전국관객수)
dat$전국관객수 = as.integer(dat$전국관객수)


dat = dat %>% filter(국적 == '한국' & 전국스크린수 >= 201) %>% 
  select(-c('순번', '전국매출액', '서울매출액', '서울관객수', '국적', '수입사', '영화유형', '영화형태', '개봉일'))
```


```{r}
dat_score = dat %>% group_by(배급사) %>% mutate(배급사점수 = mean(전국관객수))
dat_score = dat_score %>% group_by(감독) %>% mutate(감독점수 = mean(전국관객수))
dat_score = dat_score %>% group_by(제작사) %>% mutate(제작사점수 = mean(전국관객수))

dat_score %>% group_by(장르) %>% summarise(mean = mean(전국관객수),
                                         n = n()) %>% arrange(desc(mean))



par(mfrow = c(3,5))
hist(dat_score$전국관객수[dat_score$장르 == '판타지'], breaks = 10, prob = TRUE)
hist(dat_score$전국관객수[dat_score$장르 == '사극'], breaks = 10, prob = TRUE)
hist(dat_score$전국관객수[dat_score$장르 == '액션'], breaks = 10, prob = TRUE)
hist(dat_score$전국관객수[dat_score$장르 == '전쟁'], breaks = 10, prob = TRUE)
hist(dat_score$전국관객수[dat_score$장르 == 'SF'], breaks = 10, prob = TRUE)
hist(dat_score$전국관객수[dat_score$장르 == '범죄'], breaks = 10, prob = TRUE)
hist(dat_score$전국관객수[dat_score$장르 == '드라마'], breaks = 10, prob = TRUE)
hist(dat_score$전국관객수[dat_score$장르 == '코미디'], breaks = 10, prob = TRUE)
hist(dat_score$전국관객수[dat_score$장르 == '미스터리'], breaks = 10, prob = TRUE)
hist(dat_score$전국관객수[dat_score$장르 == '스릴러'], breaks = 10, prob = TRUE)
hist(dat_score$전국관객수[dat_score$장르 == '공포(호러)'], breaks = 10, prob = TRUE)
hist(dat_score$전국관객수[dat_score$장르 == '멜로/로맨스'], breaks = 10, prob = TRUE)
hist(dat_score$전국관객수[dat_score$장르 == '다큐멘터리'], breaks = 10, prob = TRUE)
hist(dat_score$전국관객수[dat_score$장르 == '가족'], breaks = 10, prob = TRUE)
hist(dat_score$전국관객수[dat_score$장르 == '애니메이션'], breaks = 10, prob = TRUE)







dat_score = dat_score[,-c(1:5)]
```

```{r}
dat_score$장르 = as.factor(dat_score$장르)
dat_score$등급 = as.factor(dat_score$등급)
dat_score$영화구분 = as.factor(dat_score$영화구분)

model = glm(전국관객수~등급+영화구분+배급사점수+감독점수+제작사점수, dat_score, family = gaussian)
model_kpold = boot::cv.glm(dat_score[,c(1,3:6)],glm.fit, K=3)

model_kpold$delta

pred = predict(model, dat_score)


plot(dat_score$전국관객수, pred)

cor(dat_score[,c(1,5,6,7)])


sqrt(mean((dat_score$전국관객수-pred)**2))
```

```{r}
# k-means cluster





```
